name: docs_examples
description: Examples used in langchaindart.dev documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  langchain: ^0.7.8+1
  langchain_anthropic: ^0.2.1+1
  langchain_chroma: ^0.2.2+1
  langchain_community: 0.3.4+1
  langchain_google: ^0.6.5+1
  langchain_mistralai: ^0.2.4+1
  langchain_ollama: ^0.3.3+1
  langchain_openai: ^0.7.5
