name: docs_examples
description: Examples used in langchaindart.dev documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  langchain: ^0.7.9
  langchain_anthropic: ^0.2.1+2
  langchain_chroma: ^0.2.2+2
  langchain_community: 0.3.4+2
  langchain_google: ^0.6.5+2
  langchain_mistralai: ^0.2.4+2
  langchain_ollama: ^0.3.3+2
  langchain_openai: ^0.7.6+1
