name: langchain_openai
description: OpenAI module for LangChain.dart.
version: 0.0.1-dev.4
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_openai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
#  dart_openai: ^2.0.1 TODO waiting for the new dart_openai version that includes OpenAI Functions
  dart_openai:
    git:
      url: https://github.com/davidmigloz/dart_openai
      ref: 0fc1574192d6263f73af1c7df9bffe5bbbd2c10f
  langchain: ^0.0.1-dev.4
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.3
