name: langchain
description: Build powerful LLM-based Dart/Flutter applications.
version: 0.0.1-dev.2
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  cross_file: ^0.3.3+4
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.3
