name: hello_world_flutter
description: A sample Flutter app integrating LangChain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  langchain: ^0.7.0
  langchain_openai: ^0.6.0+2

flutter:
  uses-material-design: true
